"""A durable checkpoint head must still route requests to the scenario's trained adapter.

A checkpointed commit moves the head to a repository release, which carries
no serving runtime load ID. Requests used to lose ``lora_path`` there and
sample the frozen base, so with ``checkpoint_every_n_versions: 1`` every step
after the first was generated by the untrained model while the trainer moved.
"""

from __future__ import annotations

import pytest
from reef_service.test_commit_log import build_training_dispatcher, wait_for_step
from reef_service.test_multi_scenario_training import AdapterRuntime, _feed

from reef.artifact import Artifact, InMemoryRepositoryBackend, LiveWeightArtifactRef
from reef.scenario.checkpoint_strategy import EveryNVersions
from reef.surface import WeightInferenceHooks, adapter_name


class CountingAdapterRuntime(AdapterRuntime):
    def __init__(self) -> None:
        super().__init__()
        self.lookups = 0

    def serving_adapter_runtime_load_id(self, scenario: str) -> str | None:
        self.lookups += 1
        return super().serving_adapter_runtime_load_id(scenario)


def _served(scenario, payload=None) -> dict:
    artifact = Artifact(scenario.current_artifact_ref(), scenario.repository)
    return scenario.surface.inference.prepare_request(artifact, "/v1/chat/completions", payload or {"messages": []})


@pytest.mark.unit
@pytest.mark.parametrize("every", [1, 2])
def test_every_head_after_training_names_the_trained_adapter(tmp_path, every) -> None:
    initial = tmp_path / "initial"
    initial.mkdir()
    runtime = CountingAdapterRuntime()
    runtime._checkpoint_dir = tmp_path / "checkpoints"
    runtime._checkpoint_dir.mkdir()
    dispatcher = build_training_dispatcher(
        runtime,
        tmp_path,
        InMemoryRepositoryBackend.factory(initial, root=tmp_path / "repository"),
        checkpoint_strategy=EveryNVersions(every),
    )
    try:
        scenario = dispatcher.get_or_create_scenario("math")
        assert "lora_path" not in _served(scenario), "before any training the frozen base is exact"
        for step in (1, 2, 3):
            _feed(dispatcher, "math", step)
            wait_for_step(dispatcher, step, scenario="math")
            scenario = dispatcher.get_or_create_scenario("math")
            checkpointed = not isinstance(scenario.current_artifact_ref(), LiveWeightArtifactRef)
            assert checkpointed == (step % every == 0)
            assert _served(scenario)["lora_path"] == adapter_name("math", f"w{step}")
    finally:
        dispatcher.close()


@pytest.mark.unit
def test_checkpoint_head_looks_up_its_adapter_once(tmp_path) -> None:
    initial = tmp_path / "initial"
    initial.mkdir()
    runtime = CountingAdapterRuntime()
    runtime._checkpoint_dir = tmp_path / "checkpoints"
    runtime._checkpoint_dir.mkdir()
    dispatcher = build_training_dispatcher(
        runtime,
        tmp_path,
        InMemoryRepositoryBackend.factory(initial, root=tmp_path / "repository"),
        checkpoint_strategy=EveryNVersions(1),
    )
    try:
        _feed(dispatcher, "math", 1)
        wait_for_step(dispatcher, 1, scenario="math")
        scenario = dispatcher.get_or_create_scenario("math")
        before = runtime.lookups
        for _ in range(5):
            assert _served(scenario)["lora_path"] == adapter_name("math", "w1")
        assert runtime.lookups == before + 1
        # A request that names another adapter is still refused.
        with pytest.raises(Exception, match="serves adapter"):
            _served(scenario, {"messages": [], "lora_path": "other"})
    finally:
        dispatcher.close()


@pytest.mark.unit
def test_runtime_routing_requires_a_scenario() -> None:
    with pytest.raises(ValueError, match="name the scenario"):
        WeightInferenceHooks(runtime=AdapterRuntime())
